### ISSUE TITLE
SSH tunnel session to vpn.lethean.space:443 appears to disconnect if idle for ~38-40mins.

### ISSUE THREAD

**Issue by bodane** [limosek/lvpn#3]
OS: Windows (tested and observed only on this OS)

- SSH tunnel session to vpn.lethean.space:443 appears to disconnect after an idle tunnel for ~38-40mins.
- Generating traffic from the client side fails and the end user side is unaware of this.
- Need to re-test again to confirm how consistent this is with not traffic being generated from the client side. Live packet capture used to confirm this behaviour.
- TCP RST flag seen from server side when this occurs.

**Comment by bodane** [comment]
Requesting to manage issues [here](https://github.com/letheanVPN/lvpn/issues) for greater community visibility.

**Comment by limosek** [comment]
OK. Switching to new link issue
