### ISSUE TITLE
SSH tunnel can suddenly drop while actively in-use (no action taken in GUI)

### ISSUE THREAD

**Issue by bodane** [limosek/lvpn#4]
OS: Windows (tested and observed only on this OS)

- SSH tunnel can suddenly drop while actively in-use and does not re-establish this existing session (no action taken in GUI).
- No noticable network outage observed during this time however am not able to confirm this as was not performing a live packet capture at the time to confirm.
- May need to replicate this issue to confirm what exactly caused this.
- Generating traffic from the client side fails and the end user side is unaware of this.

**Comment by bodane** [comment]
Requesting to manage issues [here](https://github.com/letheanVPN/lvpn/issues) for greater community visibility.

**Comment by limosek** [comment]
OK, we will follow this on new link. Closing.
